export const DEMO_PASSWORD = "MartFlow123!";

export const DEMO_STAFF = [
  {
    name: "Ayesha Khan",
    email: "manager@martflow.demo",
    role: "MANAGER" as const,
    phone: "0300-1111111",
    employeeCode: "EMP-1001",
    jobTitle: "Store manager",
    salary: 85000,
    hireDate: "2023-04-12",
  },
  {
    name: "Hamza Qureshi",
    email: "employee@martflow.demo",
    role: "EMPLOYEE" as const,
    phone: "0300-4444444",
    employeeCode: "EMP-1002",
    jobTitle: "Sales associate",
    salary: 42000,
    hireDate: "2024-01-08",
  },
  {
    name: "Bilal Ahmed",
    email: "cashier@martflow.demo",
    role: "CASHIER" as const,
    phone: "0300-2222222",
    employeeCode: "EMP-1003",
    jobTitle: "Cashier",
    salary: 40000,
    hireDate: "2024-06-02",
  },
  {
    name: "Sana Malik",
    email: "inventory@martflow.demo",
    role: "INVENTORY_STAFF" as const,
    phone: "0300-3333333",
    employeeCode: "EMP-1004",
    jobTitle: "Inventory officer",
    salary: 48000,
    hireDate: "2023-11-20",
  },
  {
    name: "Nadia Riaz",
    email: "purchases@martflow.demo",
    role: "PURCHASING" as const,
    phone: "0300-5555555",
    employeeCode: "EMP-1005",
    jobTitle: "Purchase officer",
    salary: 52000,
    hireDate: "2024-02-14",
  },
  {
    name: "Omar Sheikh",
    email: "supplier@martflow.demo",
    role: "SUPPLIER" as const,
    phone: "0300-6666666",
    employeeCode: "EMP-1006",
    jobTitle: "Vendor liaison",
    salary: 45000,
    hireDate: "2024-03-01",
  },
];

export const DEMO_CATEGORIES = [
  { id: "cat_groceries", name: "Groceries" },
  { id: "cat_beverages", name: "Beverages" },
  { id: "cat_household", name: "Household" },
  { id: "cat_personal", name: "Personal care" },
];

export const DEMO_SUPPLIERS = [
  {
    id: "sup_metro",
    name: "Metro Cash & Carry",
    company: "Metro Pakistan",
    phone: "021-11163876",
    email: "orders@metro.demo",
    address: "Korangi Creek, Karachi",
  },
  {
    id: "sup_nestle",
    name: "Nestle Distributor",
    company: "Nestle Pakistan",
    phone: "042-111637853",
    email: "trade@nestle.demo",
    address: "Shahrah-e-Faisal, Karachi",
  },
];

export const DEMO_CUSTOMERS = [
  {
    id: "cust_walkin",
    name: "Walk-in customer",
    customerType: "WALK_IN_CUSTOMER" as const,
    phone: null,
    email: null,
  },
  {
    id: "cust_ahmed",
    name: "Ahmed Raza",
    customerType: "REGISTERED_CUSTOMER" as const,
    phone: "0321-5550101",
    email: "ahmed.raza@demo.pk",
  },
  {
    id: "cust_fatima",
    name: "Fatima Noor",
    customerType: "REGISTERED_CUSTOMER" as const,
    phone: "0333-5550199",
    email: "fatima.noor@demo.pk",
  },
];

export const DEMO_PRODUCTS = [
  {
    id: "prd_milk",
    name: "Olper's Milk 1L",
    sku: "MILK-1L",
    barcode: "6281001230011",
    categoryId: "cat_groceries",
    brand: "Olper's",
    unit: "carton",
    purchasePrice: 220,
    sellingPrice: 260,
    currentStock: 48,
    minimumStock: 12,
    supplierId: "sup_nestle",
  },
  {
    id: "prd_sugar",
    name: "White Sugar 1kg",
    sku: "SUG-1KG",
    barcode: "6281001230028",
    categoryId: "cat_groceries",
    brand: "Store pack",
    unit: "bag",
    purchasePrice: 140,
    sellingPrice: 165,
    currentStock: 80,
    minimumStock: 20,
    supplierId: "sup_metro",
  },
  {
    id: "prd_oil",
    name: "Cooking Oil 5L",
    sku: "OIL-5L",
    barcode: "6281001230035",
    categoryId: "cat_groceries",
    brand: "Dalda",
    unit: "bottle",
    purchasePrice: 1850,
    sellingPrice: 2100,
    currentStock: 24,
    minimumStock: 6,
    supplierId: "sup_metro",
  },
  {
    id: "prd_atta",
    name: "Wheat Atta 10kg",
    sku: "ATTA-10",
    barcode: "6281001230042",
    categoryId: "cat_groceries",
    brand: "Sunridge",
    unit: "bag",
    purchasePrice: 1150,
    sellingPrice: 1320,
    currentStock: 18,
    minimumStock: 5,
    supplierId: "sup_metro",
  },
  {
    id: "prd_rice",
    name: "Basmati Rice 5kg",
    sku: "RICE-5",
    barcode: "6281001230059",
    categoryId: "cat_groceries",
    brand: "Kernel",
    unit: "bag",
    purchasePrice: 1450,
    sellingPrice: 1690,
    currentStock: 4,
    minimumStock: 6,
    supplierId: "sup_metro",
  },
  {
    id: "prd_pepsi",
    name: "Pepsi 1.5L",
    sku: "PEP-15",
    barcode: "6281001230066",
    categoryId: "cat_beverages",
    brand: "Pepsi",
    unit: "bottle",
    purchasePrice: 95,
    sellingPrice: 130,
    currentStock: 72,
    minimumStock: 24,
    supplierId: "sup_metro",
  },
  {
    id: "prd_water",
    name: "Mineral Water 1.5L",
    sku: "WTR-15",
    barcode: "6281001230073",
    categoryId: "cat_beverages",
    brand: "Nestle Pure Life",
    unit: "bottle",
    purchasePrice: 45,
    sellingPrice: 70,
    currentStock: 96,
    minimumStock: 24,
    supplierId: "sup_nestle",
  },
  {
    id: "prd_surf",
    name: "Surf Excel 1kg",
    sku: "SFX-1KG",
    barcode: "6281001230080",
    categoryId: "cat_household",
    brand: "Surf Excel",
    unit: "pack",
    purchasePrice: 420,
    sellingPrice: 490,
    currentStock: 30,
    minimumStock: 8,
    supplierId: "sup_metro",
  },
  {
    id: "prd_soap",
    name: "Lifebuoy Soap 160g",
    sku: "LFB-SOAP",
    barcode: "6281001230097",
    categoryId: "cat_personal",
    brand: "Lifebuoy",
    unit: "bar",
    purchasePrice: 55,
    sellingPrice: 75,
    currentStock: 120,
    minimumStock: 24,
    supplierId: "sup_metro",
  },
  {
    id: "prd_tea",
    name: "Tea Whitener 350ml",
    sku: "TEA-350",
    barcode: "6281001230103",
    categoryId: "cat_groceries",
    brand: "EveryDay",
    unit: "pack",
    purchasePrice: 85,
    sellingPrice: 110,
    currentStock: 8,
    minimumStock: 15,
    supplierId: "sup_nestle",
  },
];
